version: '2'

services:

  git-server:
    build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - ~/WAREHOUSE/keys/git:/git-server/keys
    - ~/WAREHOUSE/repositories:/git-server/repos

